version: '3.8'

services:
  docker-events-dns:
    build: .
    container_name: docker-events-dns
    restart: unless-stopped
    environment:
      - PIHOLE_URL=${PIHOLE_URL:-http://pihole.local}
      - PIHOLE_API_TOKEN=${PIHOLE_API_TOKEN}
      - DNS_LABEL=${DNS_LABEL:-dns.hostname}
      - BASE_DOMAIN=${BASE_DOMAIN:-}
      - DOCKER_HOST_IP=${DOCKER_HOST_IP}
      - ENV_PREFIX=${ENV_PREFIX}
      - INSTANCE_ID=${INSTANCE_ID}
      - STATE_DIR=${STATE_DIR:-/shared-state}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Mount shared state directory to NAS path
      # Example: /nas/docker-dns-state:/shared-state
      - ${NAS_STATE_PATH:-./state}:/shared-state
    networks:
      - docker-events-dns-network

networks:
  docker-events-dns-network:
    driver: bridge