version: '3.8'

services:
  docker-events-dns:
    build: .
    container_name: docker-events-dns
    restart: unless-stopped
    environment:
      - PIHOLE_URL=${PIHOLE_URL:-http://pihole.local}
      - PIHOLE_API_TOKEN=${PIHOLE_API_TOKEN}
      - DNS_LABEL=${DNS_LABEL:-dns.hostname}
      - BASE_DOMAIN=${BASE_DOMAIN:-}
      - DOCKER_HOST_IP=${DOCKER_HOST_IP}
      - INSTANCE_ID=${INSTANCE_ID}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./state:/tmp
    networks:
      - docker-events-dns-network

networks:
  docker-events-dns-network:
    driver: bridge